import React from 'react';

const ModelReasoning = ({ reasoning, aiExplanation }) => {
  if (!reasoning) return null;

  const isAiActive = aiExplanation && aiExplanation.ai_available;

  return (
    <div className="card reasoning-card">
      <div className="card-header" style={{ justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div className="card-header-icon">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"/>
              <line x1="12" y1="8" x2="12" y2="12"/>
              <line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg>
          </div>
          <div>
            <h3 className="card-title">Model Reasoning</h3>
            <p className="card-subtitle">
              {isAiActive ? 'Gemma LLM explanation of the decision' : 'XGBoost + SHAP explanation of the decision'}
            </p>
          </div>
        </div>

        {/* AI Status Badge */}
        {isAiActive ? (
          <div className="system-status status-online" style={{ padding: '3px 10px', fontSize: '0.68rem', borderRadius: '20px' }}>
            <span className="status-dot dot-online" style={{ width: '6px', height: '6px' }} />
            <span>Gemma Active</span>
          </div>
        ) : (
          <div className="system-status status-checking" style={{ padding: '3px 10px', fontSize: '0.68rem', borderRadius: '20px', background: 'rgba(255,255,255,0.04)' }}>
            <span className="status-dot dot-checking" style={{ width: '6px', height: '6px', background: 'var(--text-muted)' }} />
            <span>Rule Engine</span>
          </div>
        )}
      </div>

      <div className="reasoning-disclaimer" style={isAiActive ? { background: 'rgba(16, 185, 129, 0.05)', borderColor: 'rgba(16, 185, 129, 0.15)', color: '#a7f3d0' } : {}}>
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={isAiActive ? { color: 'var(--low-color)' } : {}}>
          <circle cx="12" cy="12" r="10"/>
          <line x1="12" y1="8" x2="12" y2="12"/>
          <line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
        <span>
          {isAiActive
            ? 'This analysis is generated by local Gemma 3:4B explaining XGBoost SHAP values. Final decision is governed solely by the ML model.'
            : 'This explanation is generated by the XGBoost model via SHAP analysis. It reflects model-level reasoning, not independent frontend logic.'}
        </span>
      </div>

      {!isAiActive ? (
        <p className="reasoning-body">{reasoning}</p>
      ) : (
        <div className="ai-explanation-content" style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Summary section */}
          <div>
            <h4 style={{ fontSize: '0.78rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '6px' }}>
              Decision Summary
            </h4>
            <p className="reasoning-body" style={{ color: 'var(--text-primary)', fontWeight: '500' }}>
              {aiExplanation.summary}
            </p>
          </div>

          {/* Behavioral Analysis */}
          {aiExplanation.behavioral_analysis && (
            <div>
              <h4 style={{ fontSize: '0.78rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '6px' }}>
                Behavioral Profile
              </h4>
              <p className="reasoning-body">
                {aiExplanation.behavioral_analysis}
              </p>
            </div>
          )}

          {/* Reason & Confidence Row */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', paddingTop: '12px', borderTop: '1px solid var(--border-subtle)' }}>
            <div>
              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'block', marginBottom: '2px' }}>
                LLM Assessment Reason
              </span>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
                {aiExplanation.reason}
              </p>
            </div>
            <div>
              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'block', marginBottom: '2px' }}>
                Confidence Level
              </span>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginTop: '4px' }}>
                <span className="status-dot dot-online" style={{
                  background: aiExplanation.confidence?.toLowerCase() === 'high' ? 'var(--low-color)' :
                              aiExplanation.confidence?.toLowerCase() === 'moderate' ? 'var(--medium-color)' : 'var(--text-muted)'
                }} />
                <span style={{ fontSize: '0.82rem', fontWeight: '600', color: 'var(--text-primary)' }}>
                  {aiExplanation.confidence}
                </span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ModelReasoning;
